import type { Banco } from '@/app/interface/bancoInterface'

export const bancosMock: Banco[] = [
  {
    id: 1,
    nombre: 'ESC-BR-EMT-FyR-2025 ',
    descripcion: 'ESC-BR-EMT-FyR-2025',
    fechaModificacion: '2026-05-10',
    fechaCreacion: '2026-05-01',
    reactivos: 25,
    estatus: 'activo',
    esCompartido: true,
    esProyecto: false,
    carpetaId: 1,
  },
  {
    id: 2,
    nombre:
      'Física Ikjsdhkjshdckjhskcjhk3jfcjjcjsjcjdcssdchskjcdhkjsdhckjrhcruucw48cksjhdbcuw4kcw84uwecnwcnr484ekc5765ksjhv8ref5ue8n5feifkjhkjhkjrh',
    descripcion:
      'Banco para examen parcialjdhckjdhckjsdhckjshdkjcshkcs cidcbs coi hs kh oi uhosi uo ijoi jodf hjo hk hoi uhedi u ks ho 8 jvnckjnckjdsnckjfnbkcjbnckjhackjhakrbcnkhbckjhbakjchkjshcksjhdckjshdkcjhsdkcjhskdjchksjhcksjdhckjsdhcksjdchksdjchskdjchskdjchsdkjchskjchskdjchs sdjchbsj ik hk hkjh kjbnkjuhfvkjk ujkjd hkjhkdjfh kujh iku hkuhnk dujhfk j0woirfn5 uvni8uearvma v',
    fechaModificacion: '2026-05-08',
    fechaCreacion: '2026-05-01',
    reactivos: 12,
    estatus: 'borrador',
    esCompartido: false,
    esProyecto: true,
    carpetaId: null,
  },
  {
    id: 3,
    nombre: 'MAT-ALG-LIN-2026',
    descripcion: 'Banco de reactivos para Álgebra Lineal',
    fechaModificacion: '2026-05-12',
    fechaCreacion: '2026-05-02',
    reactivos: 40,
    estatus: 'activo',
    esCompartido: false,
    esProyecto: false,
    carpetaId: 2,
  },
  {
    id: 4,
    nombre: 'QUI-ORG-PARCIAL-2',
    descripcion: 'Reactivos de química orgánica para segundo parcial',
    fechaModificacion: '2026-05-09',
    fechaCreacion: '2026-05-01',
    reactivos: 18,
    estatus: 'borrador',
    esCompartido: true,
    esProyecto: false,
    carpetaId: 1,
  },
  {
    id: 5,
    nombre: 'Proyecto Traducción Inglés B2',
    descripcion: 'Proyecto colaborativo para traducción de reactivos al inglés',
    fechaModificacion: '2026-05-11',
    fechaCreacion: '2026-05-03',
    reactivos: 60,
    estatus: 'revision',
    esCompartido: false,
    esProyecto: true,
    carpetaId: null,
  },
  {
    id: 6,
    nombre: 'BIO-CEL-EXTRAORDINARIO',
    descripcion: 'Banco de apoyo para examen extraordinario de biología celular',
    fechaModificacion: '2026-05-10',
    fechaCreacion: '2026-04-28',
    reactivos: 33,
    estatus: 'activo',
    esCompartido: false,
    esProyecto: false,
    carpetaId: 3,
  },
  {
    id: 7,
    nombre: 'Proyecto Validación Matemáticas',
    descripcion: 'Validación y revisión de reactivos del área de matemáticas',
    fechaModificacion: '2026-05-13',
    fechaCreacion: '2026-05-05',
    reactivos: 95,
    estatus: 'activo',
    esCompartido: false,
    esProyecto: true,
    carpetaId: null,
  },
  {
    id: 8,
    nombre: 'HIS-MOD-2026',
    descripcion: 'Banco de historia moderna para evaluación semestral',
    fechaModificacion: '2026-05-07',
    fechaCreacion: '2026-04-29',
    reactivos: 27,
    estatus: 'activo',
    esCompartido: true,
    esProyecto: false,
    carpetaId: 2,
  },
  {
    id: 9,
    nombre: 'FIS-MEC-REVISION',
    descripcion: 'Revisión de reactivos de mecánica clásica',
    fechaModificacion: '2026-05-12',
    fechaCreacion: '2026-05-06',
    reactivos: 44,
    estatus: 'revision',
    esCompartido: false,
    esProyecto: true,
    carpetaId: null,
  },
  {
    id: 10,
    nombre: 'ESP-LECTURA-CRITICA',
    descripcion: 'Banco de comprensión lectora y análisis crítico',
    fechaModificacion: '2026-05-04',
    fechaCreacion: '2026-04-25',
    reactivos: 21,
    estatus: 'activo',
    esCompartido: false,
    esProyecto: false,
    carpetaId: 4,
  },
  {
    id: 11,
    nombre: 'Proyecto Reactivos Medicina',
    descripcion: 'Proyecto multidisciplinario para medicina general',
    fechaModificacion: '2026-05-13',
    fechaCreacion: '2026-05-07',
    reactivos: 120,
    estatus: 'borrador',
    esCompartido: false,
    esProyecto: true,
    carpetaId: null,
  },
  {
    id: 12,
    nombre: 'ING-GRAMMAR-A2',
    descripcion: 'Banco de gramática inglesa nivel A2',
    fechaModificacion: '2026-05-08',
    fechaCreacion: '2026-05-01',
    reactivos: 29,
    estatus: 'activo',
    esCompartido: true,
    esProyecto: false,
    carpetaId: 5,
  },
]
